- name: Clone efs-utils
  git:
    repo: 'https://github.com/aws/efs-utils'
    dest: /tmp/efs-utils

- name: Make rpm
  make:
    chdir: /tmp/efs-utils
    target: rpm

- name: Find RPM file
  find:
    paths: "/tmp/efs-utils/build"
    patterns: "amazon-efs-utils*.rpm"
  register: rpm_result

- name: Install rpm
  yum:
    name: "{{ item.path }}"
    state: present
  with_items: "{{ rpm_result.files }}"

