---
# tasks file for ecs-host
- name: Download ssm agent
  get_url:
    dest: /tmp/amazon-ssm-agent.rpm
    url: https://amazon-ssm-eu-west-1.s3.amazonaws.com/latest/linux_amd64/amazon-ssm-agent.rpm

- name: Install ssm agent
  package:
    name: /tmp/amazon-ssm-agent.rpm

- name: Configure ECS config file
  blockinfile:
    create: yes
    path: /etc/ecs/ecs.config
    state: present
    block: |
      ECS_DATADIR=/data
      ECS_ENABLE_TASK_IAM_ROLE=true
      ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
      ECS_LOGFILE=/var/log/ecs-agent.log
      ECS_AVILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
      ECS_LOGLEVEL=info

- name: Configure system routing
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.conf.all.route_localnet = 1"
  register: task_result

- name: Apply new routing
  command: "sysctl -p /etc/sysctl.conf"
  when: task_result is changed

- name: Configure IPtables Prerouting Rule
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 169.254.170.2
    destination_port: 80
    to_destination: 127.0.0.1:51679
    jump: DNAT

- name: Configure IPtables Output Rule
  iptables:
    table: nat
    chain: OUTPUT
    destination: 169.254.170.2
    destination_port: 80
    protocol: tcp
    match: tcp
    jump: REDIRECT
    to_ports: 51679

- name: Save IPtables rules
  command: "iptables-save"

- name: Pull ECS Agent Container
  docker_container:
    state: present
    name: amazon-ecs-agent
    tag: latest
    reponsitory: amazon
