---
# tasks file for ecs-host
- include_tasks: efs.yml
  when: include_efs

- name: Configure ECS config file
  blockinfile:
    create: yes
    path: /etc/ecs/ecs.config
    state: present
    block: |
      ECS_DATADIR=/data
      ECS_ENABLE_TASK_IAM_ROLE=true
      ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
      ECS_LOGFILE=/var/log/ecs-agent.log
      ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
      ECS_LOGLEVEL=info
      ECS_ENGINE_TASK_CLEANUP_WAIT_DURATION=15m

- name: Configure system routing
  lineinfile:
    path: /etc/sysctl.conf
    line: "net.ipv4.conf.all.route_localnet = 1"
  register: task_result

- name: Apply new routing
  command: "sysctl -p /etc/sysctl.conf"
  when: task_result is changed

- name: Configure IPtables Prerouting Rule
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 169.254.170.2
    destination_port: 80
    to_destination: 127.0.0.1:51679
    jump: DNAT

- name: Configure IPtables Output Rule
  iptables:
    table: nat
    chain: OUTPUT
    destination: 169.254.170.2
    destination_port: 80
    protocol: tcp
    match: tcp
    jump: REDIRECT
    to_ports: 51679

- name: Save IPtables rules
  shell: "netfilter-persistent save && netfilter-persistent reload"

- name: Pull ECS Agent Container
  docker_image:
    state: present
    name: amazon/amazon-ecs-agent:latest
